version: "3"
services:
  db:
    image: postgres:16.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: wallet_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    command: sh -c "mix ecto.migrate && mix phx.server"
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
volumes:
  postgres_data: